# Generated by Django 4.1.4 on 2023-01-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchlist_itemtitle_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='itemTitle',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='itemTitle',
            field=models.CharField(max_length=80),
        ),
    ]
