# Generated by Django 4.1.4 on 2023-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('STD', 'Standard'), ('CLS', 'Classic'), ('MDN', 'Modern'), ('ELE', 'Electronic'), ('TVL', 'Travel'), ('LUX', 'Luxury'), ('ATQ', 'Antique'), ('OTH', 'Other')], default='STD', max_length=15),
        ),
    ]
